// APP MODULE
export const SET_DARK_THEME = "SET_DARK_THEME";

// AUTH
export const LOGGED = "LOGGED";
export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const USER = "USER";

// SNACKBAR
export const SET_SNACKBAR_SHOW = "SET_SNACKBAR_SHOW";
export const SET_SNACKBAR_COLOR = "SET_SNACKBAR_COLOR";
export const SET_SNACKBAR_TEXT = "SET_SNACKBAR_TEXT";
export const SET_SNACKBAR_SUBTEXT = "SET_SNACKBAR_SUBTEXT";
export const SET_SNACKBAR_TIMEOUT = "SET_SNACKBAR_TIMEOUT";

// USERS
export const SELECTED_USER = "SELECTED_USER";
export const SET_USERS = "SET_USERS";
